#默认使用配置
spring:
  profiles:
    active: dev
  thymeleaf:
    mode: HTML5
    encoding: utf-8
    servlet:
      content-type: text/html

#公共配置与profiles选择无关
mybatis:
  typeAliasesPackage: org.zj.tieba.bean
  mapperLocations: classpath:mapper/*.xml



spring:
  profiles: dev

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/tieba_db
    username: root
    password: zhangjun249
    driver-class-name: com.mysql.jdbc.Driver


